name: Test find_lowest_number Application

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies here
    - name: Test with 10 numbers
      run: |
        python find_lowest_number.py test_data/test1_input.txt output1.txt
        diff output1.txt test_data/test1_expected.txt
    - name: Test with 1 number
      run: |
        python find_lowest_number.py test_data/test2_input.txt output2.txt
        diff output2.txt test_data/test2_expected.txt
    - name: Test with blank file
      run: |
        python find_lowest_number.py test_data/test3_input.txt output3.txt
        diff output3.txt test_data/test3_expected.txt
