name: Automated Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python
      run: sudo apt-get install python3

    - name: Run Tests
      run: |
        python find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
        python find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
        python find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt

    - name: Compare Results Test 1
      run: diff test_data/test1_output.txt test_data/test1_expected.txt

    - name: Compare Results Test 2
      run: diff test_data/test2_output.txt test_data/test2_expected.txt

    - name: Compare Results Test 3
      run: diff test_data/test3_output.txt test_data/test3_expected.txt
