name: Automated Testing Workflow 

on: [push]

jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test 1 - File with 10 numbers
      run: |
        python find_lowest_number.py test_data/test1_input.txt output1.txt
        diff output1.txt test_data/test1_expected.txt
    - name: Test 2 - File with 1 number
      run: |
        python find_lowest_number.py test_data/test2_input.txt output2.txt
        diff output2.txt test_data/test2_expected.txt
    - name: Test 3 - Blank file
      run: |
        python find_lowest_number.py test_data/test3_input.txt output3.txt
        # Normalize newlines at the end of files before comparison
        echo >> output3.txt
        echo >> test_data/test3_expected.txt
        diff output3.txt test_data/test3_expected.txt || (if [ $? -eq 1 ]; then echo "Files are identical except for trailing newlines."; false; fi)
